# Generated by Django 5.2 on 2025-05-10 04:22

from django.db import migrations, models

from django.db import migrations, models

def load_educations(apps, schema_editor):
    TimelineEntry = apps.get_model('portfolio', 'timelineEntry')
    Skill = apps.get_model('portfolio', 'skill')

    education_entries = [
        {
            "entry_type": "education",
            "name": "UABC",
            "title": "Software Engineering",
            "description": "Bachelor's degree focused on software development and emerging technologies.",
            "from_date": "2022-08-01",
            "to_date": "2026-07-01",
            "skills": ["JavaScript", "Java", "Git", "GitHub", "MySQL", "Linux", "SCRUM", "C/C++"]
        },
        {
            "entry_type": "experience",
            "name": "KBA Automation",
            "title": "Technical Support",
            "description": "Provided technical assistance and troubleshooting support for automation systems and equipment, ensuring optimal performance and client satisfaction. Collaborated with engineering teams to resolve issues and implement improvements.",
            "from_date": "2023-03-01",
            "to_date": "2024-12-01",
            "skills": []
        },
        {
            "entry_type": "education",
            "name": "SDGKU",
            "title": "Full Stack Development Immersive",
            "description": "Comprehensive training program focused on full stack web development, providing practical experience in both frontend and backend technologies.",
            "from_date": "2024-11-01",
            "to_date": "2025-06-01",
            "skills": ["Flask", "Django", "React", "MongoDB","SQLite", "Python"]
        }
    ]

    for entry_data in education_entries:
        skills_names = entry_data.pop("skills", [])
        entry = TimelineEntry.objects.create(**entry_data)
        for skill_name in skills_names:
            try:
                skill = Skill.objects.get(name=skill_name)
                entry.skills.add(skill)
            except Skill.DoesNotExist:
                pass  # Ignore if skill is not found

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('experience', 'Experience'), ('education', 'Education')], max_length=20)),
                ('name', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('skills', models.ManyToManyField(related_name='timeline_entries', to='portfolio.skill')),
            ],
            options={
                'verbose_name': 'Timeline entry',
                'verbose_name_plural': 'Timeline entries',
            },
        ),
        migrations.RunPython(load_educations),
    ]
